### ISSUE TITLE
arguments containing `=` confuse this module

### ISSUE THREAD

**Issue by dakkar** [nxadm/SuperMAIN#4] opened 2020-07-06 11:03 UTC
a minimal program:
```raku
use v6.d;
use SuperMAIN;

sub MAIN(:$thing) {
    say $thing;
}
```
notice the problem:
```
$ ./minimal --thing=ab
ab
$ ./minimal --thing=a=b
ab
$ ./minimal --thing a=b
ab
```

SuperMAIN is a bit too eager, maybe?

**Comment by nxadm** [comment] 2020-07-06 11:08
Good catch. The problem is probably here:
https://github.com/nxadm/SuperMAIN/blob/master/lib/SuperMAIN.rakumod#L80

It should be straight forward to fix, thx.

**Comment by nxadm** [comment] 2020-07-06 11:08
I'll also add your examples to the tests.

**Comment by nxadm** [comment] 2021-01-05 14:20
Fixed by https://github.com/nxadm/SuperMAIN/tree/v0.1.4. Thank you!

**Closed by nxadm** 2021-01-05 14:20 UTC
